// scripts/asc-pages/generate.mjs
// Writes one baked Evidence page per org unit (Federal=1 / State=2 / LGA=3) from the shared
// template: federal index.md + per-state + per-LGA pages. Also writes per-scope geojson and
// a single org-unit search index. Root is derived from the data.
//
// Optional preview cap (for a fast local build): ASC_MAX_STATES / ASC_MAX_LGAS limit how
// many states / LGAs-per-state get pages. Unset = full build (all states, all LGAs).
import { readFileSync, writeFileSync, mkdirSync, rmSync } from 'node:fs';
import { page, leafDynamicPage } from './template.mjs';

const MAX_STATES = Number(process.env.ASC_MAX_STATES) || Infinity;
const MAX_LGAS = Number(process.env.ASC_MAX_LGAS) || Infinity;

// Tiny CSV reader — ou.csv has no embedded commas/quotes (ids, names, ints). No new dep.
function readCsv(path) {
  const [header, ...lines] = readFileSync(path, 'utf8').trim().split('\n');
  const cols = header.split(',');
  return lines.map((line) => Object.fromEntries(line.split(',').map((v, i) => [cols[i], v])));
}

// OU names carry a 2-letter lowercase prefix ("fg Nigeria", "ke Zuru LGA"); strip it for
// display. Done once here so titles, breadcrumbs, the search index and the unit label are
// all clean; map tooltips / compare tables strip the same prefix in SQL (template.mjs).
const clean = (s) => (s || '').replace(/^[a-z]{2} /, '');

const ou = readCsv('evidence/sources/census/ou.csv');
ou.forEach((o) => { o.name = clean(o.name); o.parent_name = clean(o.parent_name); });
const byId = Object.fromEntries(ou.map((o) => [o.id, o]));
const root = ou.find((o) => o.level === '1');           // the single Federal root, from the data
const ROOT = root.id;
// Federal → '/'; State → '/asc/state-<id>' (prerendered/baked); LGA → '/asc/lga/<id>' (a
// subdir so a single +layout.js can mark the whole LGA tree prerender:false → those 774 pages
// are served via the SPA fallback and rendered on-demand, keeping the baked build to ~38 pages).
const linkFor = (o) => (o.id === ROOT ? '/' : o.level === '2' ? `/asc/state-${o.id}` : `/asc/lga/${o.id}`);
const childrenOf = (id) => ou.filter((o) => o.parent_id === id).sort((a, b) => a.name.localeCompare(b.name));

const crumbsOf = (o) => {
  const chain = []; let c = o;
  while (c) { chain.unshift(c); c = c.parent_id ? byId[c.parent_id] : null; }
  return chain.map((u, i) => ({ name: u.name, link: i === chain.length - 1 ? null : linkFor(u) }));
};

// Which states/LGAs to generate (capped in preview mode).
const states = childrenOf(ROOT).slice(0, MAX_STATES);
const lgasByState = new Map(states.map((s) => [s.id, childrenOf(s.id).slice(0, MAX_LGAS)]));

// --- per-scope geojson (federal loads states; each state loads only its own LGAs) ---
const geo = JSON.parse(readFileSync('evidence/sources/census/ou.geojson', 'utf8'));
const feats = geo.features;
const fc = (features) => JSON.stringify({ type: 'FeatureCollection', features });
rmSync('evidence/static/asc', { recursive: true, force: true });
mkdirSync('evidence/static/asc', { recursive: true });
writeFileSync('evidence/static/asc/states.geojson', fc(feats.filter((f) => f.properties.level === 2)));
for (const st of states) {
  writeFileSync(`evidence/static/asc/lgas-${st.id}.geojson`,
    fc(feats.filter((f) => f.properties.level === 3 && f.properties.parent_id === st.id)));
}

// --- one org-unit search index (states + LGAs), fetched once by OrgSearch ---
const searchIndex = [];
for (const s of states) {
  searchIndex.push({ label: s.name, link: linkFor(s) });
  for (const l of lgasByState.get(s.id)) searchIndex.push({ label: `${s.name} › ${l.name}`, link: linkFor(l) });
}
writeFileSync('evidence/static/asc/search-index.json', JSON.stringify(searchIndex));
console.log(`[asc-pages] geojson: states + ${states.length} state files; search index: ${searchIndex.length} units`);

// --- pages ---
rmSync('evidence/pages/asc', { recursive: true, force: true });
mkdirSync('evidence/pages/asc/lga', { recursive: true });
// LGA leaf pages are NOT prerendered — this layout marks the whole /asc/lga/* subtree
// prerender:false, so SvelteKit bakes only Federal + States (~38 pages, avoids the 16 GB OOM)
// and serves LGAs via the adapter-static fallback (rendered client-side on demand). Evidence
// copies non-.md files from pages/ as-is, so this lands at src/pages/asc/lga/+layout.js.
writeFileSync('evidence/pages/asc/lga/+layout.js',
  '// Auto-generated by scripts/asc-pages/generate.mjs — keep LGA pages out of the prerender.\n' +
  'export const prerender = false;\n');

let n = 0;
// federal (the root IS federal, so no "unit vs federal" — Benchmark shows the Federal column only)
writeFileSync('evidence/pages/index.md', page({
  ou: root, crumbs: crumbsOf(root), childLevel: 'State',
  childLinkPrefix: '/asc/state-', geoUrl: '/asc/states.geojson', federalId: ROOT, unitLabel: '',
}));
n++;
for (const s of states) {
  writeFileSync(`evidence/pages/asc/state-${s.id}.md`, page({
    ou: s, crumbs: crumbsOf(s), childLevel: 'LGA',
    childLinkPrefix: '/asc/lga/', geoUrl: `/asc/lgas-${s.id}.geojson`, federalId: ROOT, unitLabel: s.name,
  }));
  n++;
}
// All LGAs share ONE dynamic, client-rendered route (/asc/lga/[id]) — see leafDynamicPage.
writeFileSync('evidence/pages/asc/lga/[id].md', leafDynamicPage(ROOT));
console.log(`[asc-pages] generated ${n} baked pages (federal + ${states.length} states) + 1 dynamic LGA route`);
